apiVersion: v1
kind: Service
metadata:
  name: cloudbite-frontend
  namespace: cloudbite
  labels:
    app.kubernetes.io/name: cloudbite-frontend
    app.kubernetes.io/part-of: cloudbite
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cloudbite-frontend
  ports:
    - name: http
      port: 8080
      targetPort: http
