apiVersion: v1
kind: Service
metadata:
  name: cloudbite-postgres
  namespace: cloudbite
spec:
  selector:
    app.kubernetes.io/name: cloudbite-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
